In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
data = pd.read_csv('Street_Tree_List.csv')

C:\Users\shnai\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4,10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [22]:
data['Zip Codes'].nunique

<bound method IndexOpsMixin.nunique of 0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
           ...
195672        64
195673    29,490
195674    28,859
195675    28,852
195676    28,853
Name: Zip Codes, Length: 195677, dtype: object>

In [38]:
data == np.nan

,TreeID,qLegalStatus,qSpecies,qAddress,SiteOrder,qSiteInfo,PlantType,qCaretaker,qCareAssistant,PlantDate,...,XCoord,YCoord,Latitude,Longitude,Location,Fire Prevention Districts,Police Districts,Supervisor Districts,Zip Codes,Neighborhoods (old)
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195672,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
195673,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
195674,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
195675,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
195676,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [31]:
data

,TreeID,qLegalStatus,qSpecies,qAddress,SiteOrder,qSiteInfo,PlantType,qCaretaker,qCareAssistant,PlantDate,...,XCoord,YCoord,Latitude,Longitude,Location,Fire Prevention Districts,Police Districts,Supervisor Districts,Zip Codes,Neighborhoods (old)
0,48142,Permitted Site,Tree(s) ::,NaN,252.0,Sidewalk: Curb side : Cutout,Tree,Private,NaN,07/17/2002 12:00:00 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19725,DPW Maintained,Pinus Spp :: Pine Spp,100 STAIRWAY14,3.0,Sidewalk: Curb side : Cutout,Tree,DPW,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,121399,DPW Maintained,Corymbia ficifolia :: Red Flowering Gum,349X Cargo Way,1.0,Sidewalk: Curb side : Cutout,Tree,DPW,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,46536,Permitted Site,Tree(s) ::,73 Summer St,2.0,Sidewalk: Curb side : Cutout,Tree,Private,NaN,04/01/2002 12:00:00 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,251210,DPW Maintained,Eucalyptus polyanthemos :: Silver Dollar Eucal...,1170 Ingalls St,2.0,Sidewalk: Curb side : Cutout,Tree,DPW,NaN,11/02/1992 12:00:00 AM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195672,231,DPW Maintained,Platanus x hispanica :: Sycamore: London Plane,2975 19th Ave,2.0,Sidewalk: Curb side : Cutout,Tree,DPW,NaN,03/09/2000 12:00:00 AM,...,5.990529e+06,2.095426e+06,37.733095,-122.475141,"(37.7330954514847, -122.4751412005191)",1.0,8.0,4.0,64,35.0
195673,92652,Permitted Site,Azara microphylla :: Little-Leaf Azara,2201 Baker St,18.0,Sidewalk: Property side : Cutout,Tree,Private,NaN,08/25/2009 12:00:00 AM,...,5.999814e+06,2.116396e+06,37.791208,-122.444547,"(37.791207910729526, -122.44454696545509)",13.0,6.0,1.0,"29,490",27.0
195674,108942,Permitted Site,Arbutus 'Marina' :: Hybrid Strawberry Tree,115B Prospect Ave,1.0,Sidewalk: Curb side : Cutout,Tree,Private,FUF,01/13/2015 12:00:00 AM,...,6.006936e+06,2.098797e+06,37.743289,-122.418655,"(37.7432887637665, -122.41865503445295)",2.0,7.0,7.0,"28,859",2.0
195675,143411,DPW Maintained,Platanus x hispanica :: Sycamore: London Plane,1244 MARKET ST,1.0,Sidewalk: Curb side : Cutout,Tree,Private,NaN,NaN,...,6.008078e+06,2.111483e+06,37.778185,-122.415606,"(37.77818489380947, -122.41560621944208)",7.0,2.0,9.0,"28,852",36.0
195676,15238,DPW Maintained,Lophostemon confertus :: Brisbane Box,1339 Mission St,1.0,Sidewalk: Curb side : Cutout,Tree,DPW,NaN,07/31/2012 12:00:00 AM,...,6.008169e+06,2.110575e+06,37.775699,-122.415228,"(37.77569926325394, -122.41522780193992)",8.0,2.0,9.0,"28,853",34.0

In [29]:
data['qSiteInfo'].unique()

array(['Sidewalk: Curb side : Cutout', 'Side Yard : Yard',
       'Back Yard : Yard', 'Sidewalk: Property side : Yard',
       'Median : Yard', 'Unaccepted Street : Yard', 'Front Yard : Yard',
       'Sidewalk: Curb side : Yard', 'Sidewalk: Property side : Cutout',
       'Unaccepted Street : Cutout', 'Median : Cutout',
       'Side Yard : Cutout', 'unknown : Yard', 'Back Yard : Cutout',
       'Sidewalk: Curb side : Pot', 'Sidewalk: Curb side :', 'Median :',
       ':', 'Front Yard : Pot', 'Front Yard : Cutout',
       'Unaccepted Street : Pot', ': Yard', ': Cutout', 'Front Yard :',
       'Sidewalk: Property side : Pot', 'Sidewalk: Property side :',
       'unknown : Cutout', 'Hanging basket : Cutout',
       'Sidewalk: Curb side : Hanging Pot', 'Hanging basket : Yard',
       'unknown : Pot', 'Median : Hanging Pot'], dtype=object)

There are 195677 trees

In [19]:
data['qSiteInfo']

0             Sidewalk: Curb side : Cutout
1             Sidewalk: Curb side : Cutout
2             Sidewalk: Curb side : Cutout
3             Sidewalk: Curb side : Cutout
4             Sidewalk: Curb side : Cutout
                        ...
195672        Sidewalk: Curb side : Cutout
195673    Sidewalk: Property side : Cutout
195674        Sidewalk: Curb side : Cutout
195675        Sidewalk: Curb side : Cutout
195676        Sidewalk: Curb side : Cutout
Name: qSiteInfo, Length: 195677, dtype: object

In [40]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [42]:
i = 4